"""proper init

Revision ID: 5fa3a9fb61cf
Revises: cbbfe61d0655
Create Date: 2026-03-31 19:29:04.835270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fa3a9fb61cf'
down_revision: Union[str, Sequence[str], None] = 'cbbfe61d0655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_reroute')
    op.drop_table('ships')
    op.drop_index(op.f('idx_routes_manager_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('drivers')
    op.drop_index(op.f('idx_assignment_driver_id'), table_name='assignments')
    op.drop_index(op.f('idx_assignment_route_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('roads')
    op.drop_index(op.f('idx_active_rules'), table_name='keyword_rules', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_keyword_rules_keyword_id'), table_name='keyword_rules')
    op.drop_index(op.f('uq_keyword_type_date'), table_name='keyword_rules')
    op.create_index('idx_keyword_rules_type_active', 'keyword_rules', ['type', 'is_active'], unique=False)
    op.drop_index(op.f('uq_keywords_word'), table_name='keywords')
    op.alter_column('locations', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('high', 'medium', 'low', name='prioritytype', native_enum=False),
               nullable=False)
    op.add_column('shipway_results', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('owned_ships', sa.JSON(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'driver'::text"))
    op.alter_column('users', 'threads',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('users', 'manager_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'threads',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'driver'::text"))
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'owned_ships')
    op.drop_column('users', 'location')
    op.drop_column('shipway_results', 'created_at')
    op.alter_column('locations', 'priority',
               existing_type=sa.Enum('high', 'medium', 'low', name='prioritytype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('uq_keywords_word'), 'keywords', [sa.literal_column('lower(word::text)')], unique=True)
    op.drop_index('idx_keyword_rules_type_active', table_name='keyword_rules')
    op.create_index(op.f('uq_keyword_type_date'), 'keyword_rules', ['keyword_id', 'type', 'date'], unique=True)
    op.create_index(op.f('idx_keyword_rules_keyword_id'), 'keyword_rules', ['keyword_id'], unique=False)
    op.create_index(op.f('idx_active_rules'), 'keyword_rules', ['type'], unique=False, postgresql_where='(is_active = true)')
    op.create_table('roads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('origin', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('destination', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('original_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('best_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weather_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('news_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_pkey'))
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('route_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('work_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assigned_quantity', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('best_route', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('assignments_driver_id_users_id_fk')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('assignments_manager_id_users_id_fk')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_assignment_route'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assignments_pkey'))
    )
    op.create_index(op.f('idx_assignment_route_id'), 'assignments', ['route_id'], unique=False)
    op.create_index(op.f('idx_assignment_driver_id'), 'assignments', ['driver_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('drivers_user_id_users_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('drivers_pkey'))
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('src_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('src_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dest_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dest_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('goods_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('routes_manager_id_users_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('routes_pkey'))
    )
    op.create_index(op.f('idx_routes_manager_id'), 'routes', ['manager_id'], unique=False)
    op.create_table('ships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('origin', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('destination', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('original_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('best_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weather_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('news_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shipments_pkey'))
    )
    op.create_table('road_reroute',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('done', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('road_reroute_pkey'))
    )
    # ### end Alembic commands ###
