"""update location schema

Revision ID: cbbfe61d0655
Revises: 
Create Date: 2026-03-28 20:38:25.345949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbbfe61d0655'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('shipments')
    op.drop_table('cargo')
    op.alter_column('locations', 'type',
               existing_type=postgresql.ENUM('port', 'city', 'chokepoint', 'region', name='location_type_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('locations', 'priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=True)
    op.create_index('idx_location_priority', 'locations', ['priority'], unique=False)
    op.create_index('idx_location_type', 'locations', ['type'], unique=False)
    op.create_unique_constraint('uq_location_name_country', 'locations', ['name', 'country'])
    op.drop_column('locations', 'weather_poll_interval_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('weather_poll_interval_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_location_name_country', 'locations', type_='unique')
    op.drop_index('idx_location_type', table_name='locations')
    op.drop_index('idx_location_priority', table_name='locations')
    op.alter_column('locations', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('locations', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('port', 'city', 'chokepoint', 'region', name='location_type_enum'),
               existing_nullable=False)
    op.create_table('cargo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('origin', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('optimised_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('best_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weather_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('news_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_pkey'))
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('origin', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('optimised_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('best_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weather_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('news_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shipments_pkey'))
    )
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('person_pkey'))
    )
    # ### end Alembic commands ###
