"""harmonize models and schema

Revision ID: d50d1c1ffd8e
Revises: cbbfe61d0655
Create Date: 2026-03-31 21:45:31.269885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50d1c1ffd8e'
down_revision: Union[str, Sequence[str], None] = 'cbbfe61d0655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
